# Server Port
server.port=8080

# Primary Database (etl_db) configuration
spring.datasource.primary.jdbc-url=jdbc:mysql://127.0.0.1:3306/etl_db
spring.datasource.primary.username=root
spring.datasource.primary.password=2004
spring.datasource.primary.driver-class-name=com.mysql.cj.jdbc.Driver

# Source Database configuration
spring.datasource.source.jdbc-url=jdbc:mysql://localhost:3306/source_db
spring.datasource.source.username=root
spring.datasource.source.password=2004
spring.datasource.source.driver-class-name=com.mysql.cj.jdbc.Driver

# Target Database configuration
spring.datasource.target.jdbc-url=jdbc:mysql://localhost:3306/target_db
spring.datasource.target.username=root
spring.datasource.target.password=2004
spring.datasource.target.driver-class-name=com.mysql.cj.jdbc.Driver

# File paths
etl.csv.path=C:/Users/ansh.saxena_cloudsuf/Desktop/etlproject/src/data/employees.csv
etl.json.path=C:/Users/ansh.saxena_cloudsuf/Desktop/etlproject/src/data/employees.json
etl.invalid.path=C:/Users/ansh.saxena_cloudsuf/Desktop/etlproject/src/data/invalid.csv
